#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.

# Break on errors
set -e

# Settings
VERSION="0.1"
SCRIPT_PATH="$(dirname "$(realpath -- "$0")")"
QC_CBSP_TOOLS=${SCRIPT_PATH}/cbsp-boot-utilities/uefi_capsule_generation
OUT_DIR="$(realpath -- ".")"
MIN_PYTHON_VER="3.10.0"
KEYS_PATH="OEM-KEYS"
FMP_CA_DIR="demoCA"
FW_VER="0.0.1.0"
LFW_VER="0.0.0.0"
FV_UPDATE_FILE="${QC_CBSP_TOOLS}/FvUpdate.xml"
CAPSULE_FILE="capsule_file.cap"

# Flags
DEBUG=0
QUIET=0

parse_args()
{
    while [ $# -gt 0 ]
    do
        case $1 in
        --debug)
            DEBUG=1
            echo "FLAG: Debug: enabled"
            shift
            ;;
        --capsule-file)
            CAPSULE_FILE=$2
            echo "FLAG: CAPSULE_FILE: ${CAPSULE_FILE}"
            shift
            shift
            ;;
        --fv-update-file)
            FV_UPDATE_FILE=$2
            echo "FLAG: FV_UPDATE_FILE: ${FV_UPDATE_FILE}"
            shift
            shift
            ;;
        --fw-ver)
            FW_VER=$2
            echo "FLAG: FW_VER: ${FW_VER}"
            shift
            shift
            ;;
        --keys-path)
            KEYS_PATH=$2
            echo "FLAG: KEYS_PATH: ${KEYS_PATH}"
            shift
            shift
            ;;
        --lfw-ver)
            LFW_VER=$2
            echo "FLAG: LFW_VER: ${LFW_VER}"
            shift
            shift
            ;;
        --out-dir)
            OUT_DIR="$(realpath -- "$2")"
            echo "FLAG: OUT_DIR: ${OUT_DIR}"
            shift
            shift
            ;;
        --version)
            echo "Version: ${VERSION}"
            exit 0
            ;;
        --help)
            echo "Usage parameters:"
            echo "--debug: enables debug logging"
            echo "--capsule-file: filename of the capsule generated under capsule/ (default: ${CAPSULE_FILE})"
            echo "--fv-update-file: full path to the FvUpdate.xml file (default: ${FV_UPDATE_FILE})"
            echo "--fw-ver: FwVer parameter for generating SYSFW_VERSION.bin (default: ${FW_VER})"
            echo "--keys-path: path to keys directory generated by genkeys script (default: ${KEYS_PATH})"
            echo "--lfw-ver: LFwVer parameter for generating SYSFW_VERSION.bin (default: ${LFW_VER})"
            echo "--out-dir: output directory for signed images (default: ${OUT_DIR})"
            exit 0
            ;;
        *)
            shift
            ;;
        esac
    done
}

parse_args "$@"

debug_log()
{
    if [ "${DEBUG}" -eq 1 ]; then
        echo "DEBUG: $1"
    fi
}

log()
{
    if [ "${QUIET}" -ne 1 ]; then
        echo "$1"
    fi
}

version_greater_equal()
{
    printf '%s\n%s\n' "$2" "$1" | sort --check=quiet --version-sort
}

log "Check for python 3.x"
command -v python3 >/dev/null 2>&1 || { echo >&2 "Missing python3.  Aborting."; exit 1; }
log "> python3 found."

PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
log "Check python3 version (${PYTHON_VERSION}) >= ${MIN_PYTHON_VER}"
version_greater_equal "${PYTHON_VERSION}" ${MIN_PYTHON_VER} || { echo >&2 "Need at least python3 ${MIN_PYTHON_VER}.  Aborting."; exit 1; }
log "> python3 version == ${PYTHON_VERSION}"

## Pre-requisites: https://github.com/quic/cbsp-boot-utilities/tree/main/uefi_capsule_generation#31-pre-requisites-to-run-the-tool
## TODO: check for the following Python packages:
## pip install --break-system-packages --user validators

[ ! -d "${KEYS_PATH}"  ] && { echo >&2 "ERROR: Directory for KEYS_PATH is not found: ${KEYS_PATH}.  Use --keys-path to set.  Aborting."; exit 1; }
[ ! -d "${KEYS_PATH}/${FMP_CA_DIR}"  ] && { echo >&2 "ERROR: Directory for KEYS_PATH/FMP_CA_DIR is not found: ${KEYS_PATH}/${FMP_CA_DIR}.  You might need to re-generate keys.  Aborting."; exit 1; }
[ ! -d "${OUT_DIR}" ] && { echo >&2 "ERROR: OUT_DIR not found: ${OUT_DIR}.  Aborting."; exit 1; }

# Set CERT path
CERT_PATH=${KEYS_PATH}/${FMP_CA_DIR}
log "Using keys: ${KEYS_PATH}/${FMP_CA_DIR}"

# Set CAPSULE path
CAPSULE_DIR="${OUT_DIR}/capsule"
log "Capsule location: ${CAPSULE_DIR}"

log "Fetching capsule update dependencies"
python3 ${QC_CBSP_TOOLS}/capsule_setup.py
log "> Done"

log "Clear old capsule gen dir"
rm -rf ${CAPSULE_DIR}
mkdir -p ${CAPSULE_DIR}

cd ${CAPSULE_DIR}

log "Create firmware QC container"
python3 ${QC_CBSP_TOOLS}/SYSFW_VERSION_program.py -Gen -FwVer ${FW_VER} -LFwVer ${LFW_VER} -O SYSFW_VERSION.bin
python3 ${QC_CBSP_TOOLS}/SYSFW_VERSION_program.py  --PrintAll SYSFW_VERSION.bin
log "> Done"

log "Process components and QC container"
python3 ${QC_CBSP_TOOLS}/FVCreation.py firmware.fv "-FvType" "SYS_FW" "${FV_UPDATE_FILE}" SYSFW_VERSION.bin ${OUT_DIR}
log "> Done"

log "Populate JSON configuration"
python3 ${QC_CBSP_TOOLS}/UpdateJsonParameters.py \
    -j config.json \
    -f SYS_FW -b SYSFW_VERSION.bin \
    -pf firmware.fv \
    -p ${CERT_PATH}/QcFMPCert.pem \
    -x ${CERT_PATH}/QcFMPRoot.pub.pem \
    -oc ${CERT_PATH}/QcFMPSub.pub.pem \
    -g 6F25BFD2-A165-468B-980F-AC51A0A45C52
log "> Done"


log "Generating capsule: ${CAPSULE_FILE}"
python3 ${QC_CBSP_TOOLS}/GenerateCapsule.py \
    -e -j config.json -o ${CAPSULE_FILE} --capflag PersistAcrossReset -v
log "> Done"

log "Dumping capsule: ${CAPSULE_FILE}"
python3 ${QC_CBSP_TOOLS}/GenerateCapsule.py --dump-info ${CAPSULE_FILE}
log "> Done"
