#!/bin/sh

# Break on errors
set -e

# Settings
VERSION="0.1"
KEYS_PATH="OEM-KEYS"
KEYS_ROOT_CERT="qpsa_rootca###.cer"
KEYS_CA_CERT="qpsa_attestca###.cer"
KEYS_CA_KEY="qpsa_attestca###.key"
KEYS_ROOTS_HASH="sha384_roots_hash.txt"
ROOT_CERT_TOTALNUM=1
SIGNING_KEY_INDEX=0
OUT_DIR="./"
ANTI_ROLLBACK_VERSION=0x0
SECTOOL=""
SECURITY_PROFILE=""
SCRIPT_PATH=$(dirname "$0")

# Flags
DEBUG=0
FORCE=0
QUIET=0

function parse_args()
{
    while [ $# -gt 0 ]
    do
        case $1 in
        --anti-rollback-version)
            if echo "$2" | grep -Eq '^0x?[0-9a-fA-F]+$'; then
                ANTI_ROLLBACK_VERSION=$2
                echo "FLAG: ANTI_ROLLBACK_VERSION: ${ANTI_ROLLBACK_VERSION}"
            else
                echo >&2 "ERROR: ANTI_ROLLBACK_VERSION is not a valid hex number: $2.  Aborting."
                exit 1
            fi
            shift
            shift
            ;;
        --debug)
            DEBUG=1
            echo "FLAG: Debug: enabled"
            shift
            ;;
        --force)
            FORCE=1
            echo "FLAG: Force overwrite: enabled"
            shift
            ;;
        --keys-path)
            KEYS_PATH=$2
            echo "FLAG: KEYS_PATH: ${KEYS_PATH}"
            shift
            shift
            ;;
        --keys-root-cert-filename)
            KEYS_ROOT_CERT=$2
            echo "FLAG: KEYS_ROOT_CERT: ${KEYS_ROOT_CERT}"
            shift
            shift
            ;;
        --keys-ca-cert-filename)
            KEYS_CA_CERT=$2
            echo "FLAG: KEYS_CA_CERT: ${KEYS_CA_CERT}"
            shift
            shift
            ;;
        --keys-ca-key-filename)
            KEYS_CA_KEY=$2
            echo "FLAG: KEYS_CA_KEY: ${KEYS_CA_KEY}"
            shift
            shift
            ;;
        --keys-root-hash-filename)
            KEYS_ROOTS_HASH=$2
            echo "FLAG: KEYS_ROOTS_HASH: ${KEYS_ROOTS_HASH}"
            shift
            shift
            ;;
        --out-dir)
            OUT_DIR=$2
            echo "FLAG: OUT_DIR: ${OUT_DIR}"
            shift
            shift
            ;;
        --quiet)
            QUIET=1
            echo "FLAG: Quiet mode"
            shift
            ;;
        --root-cert-totalnum)
            case $2 in
                1)
                    ROOT_CERT_TOTALNUM=$2
                    echo "FLAG: ROOT_CERT_TOTALNUM: ${ROOT_CERT_TOTALNUM}"
                    ;;
                *)
                    echo >&2 "ERROR: ROOT_CERT_TOTALNUM values can only be 1.  Aborting."
                    exit 1
                    ;;
            esac
            shift
            shift
            ;;
        --sectoolv2)
            SECTOOL=$2
            echo "FLAG: SECTOOL: ${SECTOOL}"
            shift
            shift
            ;;
        --security-profile)
            SECURITY_PROFILE=$2
            echo "FLAG: SECURITY_PROFILE: ${SECURITY_PROFILE}"
            shift
            shift
            ;;
        --signing-key-index)
            case $2 in
                0 | 1 | 2 | 3)
                    SIGNING_KEY_INDEX=$2
                    echo "FLAG: SIGNING_KEY_INDEX: ${SIGNING_KEY_INDEX}"
                    ;;
                *)
                    echo >&2 "ERROR: SIGNING_KEY_INDEX values can be 0,1,2 or 3: $2.  Aborting."
                    exit 1
                    ;;
            esac
            shift
            shift
            ;;
        --version)
            echo "Version: ${VERSION}"
            exit 0
            ;;
        --help)
            echo "Usage parameters:"
            echo "--anti-rollback-version: hex value supplied to 'sectoolsv2 secure-image' --anti-rollback-version param"
            echo "  (default: ${ANTI_ROLLBACK_VERSION})"
            echo "--debug: enables debug logging"
            echo "--force: force overwrite files (dangerous!)"
            echo "--keys-path: path to keys directory generated by genkeys script (default: ${KEYS_PATH}"
            echo "--keys-root-cert-filename: root cert filename (default: ${KEYS_ROOT_CERT})"
            echo "--keys-ca-cert-filename: ca cert filename (default: ${KEYS_CA_CERT})"
            echo "--keys-ca-key-filename: ca key filename (default: ${KEYS_CA_KEY})"
            echo "--keys-root-hash-filename: roots hash filename (default: ${KEYS_ROOTS_HASH})"
            echo "--out-dir: output directory for signed images (default: ${OUT_DIR})"
            echo "--quiet: disable normal logging"
            echo "--root-cert-totalnum: set # of root certs to use. 1-4 allowed (default: 4)"
            echo "--sectoolv2: path to sectoolv2 binary"
            echo "--security-profile: path to *-security-profile.xml"
            echo "--signing-key-index: which CA key index to use for signing (default: ${SIGNING_KEY_INDEX})"
            exit 0
            ;;
        *)
            shift
            ;;
        esac
    done
}

parse_args "$@"

function debug_log()
{
    if [ "${DEBUG}" -eq 1 ]; then
        echo "DEBUG: $1"
    fi
}

function log()
{
    if [ "${QUIET}" -ne 1 ]; then
        echo "$1"
    fi
}

function sign_verify()
{
    debug_log "Found $1"

    file="$(basename $1)"
    filedir="$(dirname "$1")"

    sign_id=$(${SECTOOL} secure-image --inspect $1 | grep "| Software ID:" | cut -d'|' -f3)
    if [ -z "${sign_id}" ]; then
        log "> WARN: $1 does not contain signatures.  Skipping."
        return 0
    fi

    # Lookup the IMAGE-ID from mapping
    IMAGE_ID=$(echo -e "${IMAGE_ID_MAPPING}" | grep "${file}" | cut -d' ' -f2)
    PIL_SPLIT_FLAG=$(echo -e "${IMAGE_ID_MAPPING}" | grep "${file}" | cut -d' ' -f3)
    debug_log "> IMAGE_ID: ${IMAGE_ID}"
    if [ -z "${IMAGE_ID}" ] || [ "${IMAGE_ID}" == "UNKNOWN" ]; then
        echo >&2 "ERROR: Unable to find IMAGE-ID mapping for ${file}.  Aborting."
        exit 1
    fi

    if [ "${IMAGE_ID}" == "SKIP" ]; then
        log "Skip signing of ${file}"
        return 0
    fi

    # Check to make sure the IMAGE_ID is valid for the supplied security-profile
    if echo "${VALID_IMAGE_ID}" | grep "${IMAGE_ID}" >/dev/null 2>&1; then
        debug_log "> ${IMAGE_ID} is a valid IMAGE_ID"
    else
        echo >&2 "WARN: IMAGE_ID(${IMAGE_ID}) is not valid for this security-profile(${SECURITY_PROFILE}).  Skipping."
        return 0
    fi

    PIL_SPLIT=""
    if [ "${PIL_SPLIT_FLAG}" -eq "1" ]; then
        debug_log "> Found PIL-SPLIT flag for $1."
        PIL_SPLIT="--pil-split --pil-split-outdir=${filedir}"
    fi

    log "Signing $1"
    ${SECTOOL} secure-image ${VERBOSE} \
        --sign $1 --image-id=${IMAGE_ID} \
        --security-profile ${SECURITY_PROFILE} \
        --anti-rollback-version=${ANTI_ROLLBACK_VERSION} \
        --signing-mode LOCAL \
        ${PIL_SPLIT} \
        ${ROOT_CERT_INDEX} \
        --root-certificate ${ROOT_CERT_LIST} \
        --ca-certificate=${KEYS_CA_CERT_FILENAME} --ca-key=${KEYS_CA_KEY_FILENAME} \
        --outfile $1

    log "> Verifying root hash of $1"
    ${SECTOOL} secure-image ${VERBOSE} --verify-root ${ROOT_CERT_HASH} $1
    if [ $? -ne 0 ]; then
        echo >&2 "ERROR: Root hash of $1 failed verification.  Aborting."
        exit 1
    fi

    # verify pil-split file
    if [ "${PIL_SPLIT_FLAG}" -eq "1" ]; then
        mdt_file="${filedir}/${file%.*}.mdt"
        log "> Verifying root hash of ${mdt_file}"
        ${SECTOOL} secure-image ${VERBOSE} --verify-root ${ROOT_CERT_HASH} ${mdt_file}
        if [ $? -ne 0 ]; then
            echo >&2 "ERROR: Root hash of ${mdt_file} failed verification.  Aborting."
            exit 1
        fi
    fi

    log "> Verified."
}

[ -z "${SECTOOL}"  ] && { echo >&2 "ERROR: Missing --sectoolv2 parameter.  Aborting."; exit 1; }
[ -z "${SECURITY_PROFILE}"  ] && { echo >&2 "ERROR: Missing --security-profile parameter.  Aborting."; exit 1; }
[ ! -f "${SECURITY_PROFILE}"  ] && { echo >&2 "ERROR: File for security-profile could not be found: ${SECURITY_PROFILE}  Aborting."; exit 1; }
[ ! -d "${KEYS_PATH}"  ] && { echo >&2 "ERROR: Directory for KEYS_PATH is not found: ${KEYS_PATH}.  Use --keys-path to set.  Aborting."; exit 1; }
[ ! -d "${OUT_DIR}" ] && { echo >&2 "ERROR: OUT_DIR not found: ${OUT_DIR}.  Aborting."; exit 1; }

if [ "${SIGNING_KEY_INDEX}" -ge "${ROOT_CERT_TOTALNUM}" ]; then
        echo >&2 "ERROR: --signing-key-index(${SIGNING_KEY_INDEX}) cannot be equal or greater to --root-cert-totalnum(${ROOT_CERT_TOTALNUM}).  Aborting."
        exit 1
fi

if [ ! -f "${KEYS_PATH}/${KEYS_ROOTS_HASH}" ]; then
    echo >&2 "ERROR: Cannot find roots hash file: ${KEYS_PATH}/${KEYS_ROOTS_HASH}.  Aborting."
    exit 1
fi
log "Reading the sha384 hash of the root certificate(s)."
ROOT_CERT_HASH="0x$(cat ${KEYS_PATH}/${KEYS_ROOTS_HASH} | cut -d' ' -f2)"
log "> Done"

# Define a newline
newline=$'\n'

# Get list of valid image IDs from the security profile
log "Creating a list of valid IMAGE-IDs"
OIFS="${IFS}"
IFS=${newline}
VALID_IMAGE_ID=""
SKIP_FIRST=0
for line in $(${SECTOOL} secure-image --available-image-ids --security-profile ${SECURITY_PROFILE})
do
    if [ "${SKIP_FIRST}" -eq 0 ]; then
        SKIP_FIRST=1
        continue
    fi
    NEW_ID=$(echo "${line}" | cut -c4-)
    debug_log "> Adding: ${NEW_ID}"
    VALID_IMAGE_ID+="${NEW_ID}"
    VALID_IMAGE_ID+=$'\n'
done
IFS="${OIFS}"
log "> Done"

# <filename> <image_id> <pil-split-flag>
IMAGE_ID_MAPPING="\
a660_zap.mbn GPU-MICRO-CODE 1 ${newline}\
adsp.mbn ADSP 1 ${newline}\
aop.mbn AOP 0 ${newline}\
cdsp.mbn CDSP 1 ${newline}\
cpucp.elf CPUCP 0 ${newline}\
devcfg.mbn TZ-DEVCFG 0 ${newline}\
hypvm.mbn QHEE 0 ${newline}\
imagefv.elf UEFIFV 0 ${newline}\
ipa_fws.mbn IPA-FW 1 ${newline}\
loadalgota64.mbn TZ-APP-OEM 1 ${newline}\
msbtfw11.mbn SKIP 0 ${newline}\
multi_image.mbn OEM-MISC 0 ${newline}\
prog_firehose_ddr.elf DEVICE-PROGRAMMER 0 ${newline}\
prog_firehose_lite.elf DEVICE-PROGRAMMER 0 ${newline}\
qupv3fw.elf QUPV3 0 ${newline}\
sec.elf SEC-ELF 0 ${newline}\
shrm.elf SHRM 0 ${newline}\
tz.mbn TZ 0 ${newline}\
uefi.elf UEFI 0 ${newline}\
uefi_sec.mbn TZ-APP-OEM 0 ${newline}\
vpu20_1v.mbn VENUS-FW 0 ${newline}\
vpu30_4v.mbn VENUS-FW 0 ${newline}\
vpu30_4v_16mb.mbn VENUS-FW 0 ${newline}\
wpss.mbn WPSS 1 ${newline}\
xbl_config.elf XBL-CONFIG 0 ${newline}\
xbl_config_gunyah.elf XBL-CONFIG 0 ${newline}\
xbl_config_kvm.elf XBL-CONFIG 0 ${newline}\
xbl.elf XBL 0 ${newline}\
XblRamdump.elf XBL-RAM-DUMP 0 ${newline}\
DigestsToSign.bin.mbn VIP 0 ${newline}\
FD02C9DA-306C-48C7-A49C-BBD827AE86EE.mbn TZ-APP-OEM 0 ${newline}\
"

# Create a list of root certificates
ROOT_CERT_LIST=""
key=0
# Loop through ROOT_CERT_TOTALNUM
while [ "${key}" -lt ${ROOT_CERT_TOTALNUM} ]
do
    KEY_FILENAME=$(echo "${KEYS_PATH}/${KEYS_ROOT_CERT}" | sed "s/###/${key}/g")
    if [ ! -f "${KEY_FILENAME}" ]; then
        echo >&2 "ERROR: Cannot find root certificate: ${KEY_FILENAME}.  Aborting."
        exit 1
    fi
    ROOT_CERT_LIST+=" ${KEY_FILENAME}"
    # increment key counter
    key=$((key + 1))
done

KEYS_CA_KEY_FILENAME=$(echo "${KEYS_PATH}/${KEYS_CA_KEY}" | sed "s/###/${SIGNING_KEY_INDEX}/g")
if [ ! -f "${KEYS_CA_KEY_FILENAME}" ]; then
    echo >&2 "ERROR: Cannot find CA key: ${KEYS_CA_KEY_FILENAME}.  Aborting."
    exit 1
fi

KEYS_CA_CERT_FILENAME=$(echo "${KEYS_PATH}/${KEYS_CA_CERT}" | sed "s/###/${SIGNING_KEY_INDEX}/g")
if [ ! -f "${KEYS_CA_CERT_FILENAME}" ]; then
    echo >&2 "ERROR: Cannot find CA certificate: ${KEYS_CA_CERT_FILENAME}.  Aborting."
    exit 1
fi

# Signing data for more than 1 root key
ROOT_CERT_INDEX=""
if [ "${ROOT_CERT_TOTALNUM}" -gt 1 ]; then
    ROOT_CERT_INDEX="--root-certificate-index ${SIGNING_KEY_INDEX}"
fi

VERBOSE=""
if [ "${DEBUG}" -eq 1 ]; then
    VERBOSE="--verbose"
fi

log "Searching for MDT files without matching MBN files."
file_list=$(find ${OUT_DIR} -iname "*.mdt")
mbn_create_list=""
for file in ${file_list}
do
    mbn_file=$(basename "${file%.*}.mbn")
    mbn_base=$(dirname "${file}")
    debug_log "> Checking for ${mbn_base}/${mbn_file}"
    if [ ! -f "${mbn_base}/${mbn_file}" ]; then
        log "> ${mbn_base}/${mbn_file} not found!  Creating from MDT fragments."
        ${SCRIPT_PATH}/bin/pil-squasher "${mbn_base}/${mbn_file}" ${file}
	mbn_create_list+=" ${mbn_base}/${mbn_file}"
    else
        debug_log "> Found ${mbn_base}/${mbn_file}"
    fi
done

log "Searching for MBN files to sign."
file_list=$(find ${OUT_DIR} -iname "*.mbn")
for file in ${file_list}
do
    sign_verify "${file}"
done

log "Searching for ELF files to sign."
file_list=$(find ${OUT_DIR} -iname "*.elf")
for file in ${file_list}
do
    sign_verify ${file} 0
done

log "Image signing complete."
